import { useState } from 'react';
import './App.css';
import Task1App from './task1/Task1App';
import Task2App from './task2/Task2App';

// Task switcher — DO NOT EDIT THIS FILE.
// Interns: work only inside src/task1/ or src/task2/.
function App() {
  const [activeTask, setActiveTask] = useState('task1');

  return (
    <div className="App">
      <header className="app-header">
        <h1>React Practice Tasks</h1>
        <nav className="task-tabs">
          <button
            type="button"
            className={activeTask === 'task1' ? 'tab active' : 'tab'}
            onClick={() => setActiveTask('task1')}
          >
            Task 1 — Feedback Form
          </button>
          <button
            type="button"
            className={activeTask === 'task2' ? 'tab active' : 'tab'}
            onClick={() => setActiveTask('task2')}
          >
            Task 2 — GitHub Search
          </button>
        </nav>
      </header>

      <main className="app-main">
        {activeTask === 'task1' ? <Task1App /> : <Task2App />}
      </main>
    </div>
  );
}

export default App;
