import { useState } from 'react';
import './App.css';
import Task1App from './task1/Task1App';
import Task2App from './task2/Task2App';
import Task3App from './task3/Task3App';
import Task4App from './task4/Task4App';

// Task switcher — DO NOT EDIT THIS FILE.
// Interns: work only inside your own src/taskN/ folder.
const TASKS = [
  { id: 'task1', label: 'Task 1 — Feedback Form', Component: Task1App },
  { id: 'task2', label: 'Task 2 — GitHub Search', Component: Task2App },
  { id: 'task3', label: 'Task 3 — Expense Tracker', Component: Task3App },
  { id: 'task4', label: 'Task 4 — Product Catalog', Component: Task4App },
];

function App() {
  const [activeTask, setActiveTask] = useState('task3');

  const active = TASKS.find((task) => task.id === activeTask);
  const ActiveComponent = active.Component;

  return (
    <div className="App">
      <header className="app-header">
        <h1>React Practice Tasks</h1>
        <nav className="task-tabs">
          {TASKS.map((task) => (
            <button
              key={task.id}
              type="button"
              className={task.id === activeTask ? 'tab active' : 'tab'}
              onClick={() => setActiveTask(task.id)}
            >
              {task.label}
            </button>
          ))}
        </nav>
      </header>

      <main className="app-main">
        <ActiveComponent />
      </main>
    </div>
  );
}

export default App;
